### ISSUE TITLE
errors/questions running in Mac M1 Docker Desktop

### ISSUE THREAD

**Issue by kirlen** [decc/twenty-fifty-new-look#7]
Has anyone been able to get this up and running on Mac M1?? I'm running into:
`failed to initialize Lua VM`
I believe this is specific to M1 with phusion/passenger-ruby21. I tried adding docker-compose.yml with this, but no luck: 
```
version: "3.8"
services:
  app:
    build:
      context: .
    platform: "linux/amd64"
    ports:
      - "8080:80"
    # ...
```
